spring:
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mods_trades
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
